---
title: "exercise1"
author: "202047721"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import "CO2" Built in Dataset

#### Description

The CO2 data frame has 84 rows and 5 columns of data from an experiment on the cold tolerance of the grass species Echinochloa crus-galli.For more info see - [here](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/zCO2.html)

```{r}
co2df <- CO2 # Assigned CO" dataset to co2df for further analysis
head(co2df, 10)
```

## First Data Transformation - Creating a New Column 'uptake_bucket'

```{r}
# Define the transformation function
transform_data <- function(data) {
  # Create a new column 'uptake_bucket' to categorize uptake into 10-wide buckets (0-9, 10-19, etc.)
  data$uptake_bucket <- cut(  
    data$uptake,
    breaks = seq(0, max(data$uptake, na.rm = TRUE) + 10, by = 10),  # Define the breakpoints for the buckets
    right = FALSE,  # Set the interval type to be left-closed and right-open
    labels = paste0(seq(0, max(data$uptake, na.rm = TRUE), by = 10), "-", seq(10, max(data$uptake, na.rm = TRUE) + 10, by = 10) - 1) # Define the labels for the buckets
  )
  
  # Return the transformed dataset
  return(data)
}

# Transform the CO2 dataset
co2df <- transform_data(co2df)

# Display the first 10 rows of the transformed dataset
head(co2df, 10)
```





